### ISSUE TITLE
client.close() not working

### ISSUE THREAD

**Issue by usureshb** [fh1ch/node-bacstack#114]
Node Version: `8.9.1`

Node BACstack Version: Latest version

My code snippet is as follow : 
 var reqArr2 = [
    {objectIdentifier: {type: 8, instance: 4194303}, propertyReferences: [{propertyIdentifier: 77}]}
  ];    
  client.readPropertyMultiple(config.ControllerIPAddress.trim(), reqArr2, function(err, value) {
    console.log('device :',JSON.stringify(value))
    var d = value.values[0].values[0].value[0].value
    console.log('>>>>>> device name '+d);
    deviceName = "Device_"+d;
    client.close();
});

I am getting this error saying close() is not supported.

TypeError: client.close is not a function
    at /Users/suresh/Bacnet/facilioagent/fetchdata.js:32:12
    at /Users/suresh/Bacnet/facilioagent/node_modules/bacstack/lib/bacnet-client.js:314:7
    at invokeStore.(anonymous function) (/Users/suresh/Bacnet/facilioagent/node_modules/bacstack/lib/bacnet-client.js:56:7)
    at invokeCallback (/Users/suresh/Bacnet/facilioagent/node_modules/bacstack/lib/bacnet-client.js:44:26)
    at handlePdu (/Users/suresh/Bacnet/facilioagent/node_modules/bacstack/lib/bacnet-client.js:189:11)
    at handleNpdu (/Users/suresh/Bacnet/facilioagent/node_modules/bacstack/lib/bacnet-client.js:235:5)
    at self.receiveData (/Users/suresh/Bacnet/facilioagent/node_modules/bacstack/lib/bacnet-client.js:246:7)
    at Socket.<anonymous> (/Users/suresh/Bacnet/facilioagent/node_modules/bacstack/lib/bacnet-transport.js:11:24)
    at emitTwo (events.js:126:13)
    at Socket.emit (events.js:214:7)

**Comment by mtoko** [comment]
I suspect I have a similar issue. If I create multiple instances of bacstack my application works, but if I use a single instance and use client.close after each read then this does not work

**Comment by fh1ch** [comment]
@usureshb the error `client.close` strongly hints, that the `bacstack` class itself wasn't the properly initialised. The mentioned function (see https://github.com/fh1ch/node-bacstack/blob/master/lib/client.js#L1190) is a member function of the `bacstack` class and has therefore to be available, as long as the object exists. Furthermore, this function is tested successfully countless times as part of the unit, integration and compliance-tests (see https://github.com/fh1ch/node-bacstack/blob/master/test/compliance/who-is.spec.js#L9). Please ensure that the bacstack is properly initialised (as described in the readme, see https://github.com/fh1ch/node-bacstack#example).

@usureshb @mtoko feel free to re-open this issue, if the error still persist. Please also provide a code-example on how the bacstack is initialised.
