### ISSUE TITLE
Binary Output writing issue:  Error: BacnetError - Class:1 - Code:31

### ISSUE THREAD

**Issue by Panibrat** [fh1ch/node-bacstack#115]
Node Version: `10.5.0`

Node BACstack Version: `0.0.1-beta.12`

I Can read Binary Output. Response:
```{ len: 11,
  objectId: { type: 4, instance: 3000412 },
  property: { propertyIdentifier: 85, propertyArrayIndex: 4294967295 },
  valueList: [ { len: 2, type: 9, value: 1 } ] }
```
My Code to write this point:

```
const bacnet = require('bacstack');
const client = new bacnet();

const valueToSave = 1;
client.writeProperty(
    '192.168.1.207',
    4, //4 = Binary Output
    '3000412',
    85,
    16,
    [
        {
            type: bacnet.enum.BacnetApplicationTags.BACNET_APPLICATION_TAG_ENUMERATED,
            value: valueToSave,
        },
    ],
    (err, value) => {
        if (err) {
            console.log('writePropertyError: ', err);
        } else {
            console.log('writeProperty: ', value);
        }
    },
);

```
Response:
```
Error: BacnetError - Class:1 - Code:31
    at processError (C:\WEBSTORM\BACnetServerV2\node_modules\bacstack\lib\bacnet-client.js:95:30)
    at handlePdu (C:\WEBSTORM\BACnetServerV2\node_modules\bacstack\lib\bacnet-client.js:309:9)
    at handleNpdu (C:\WEBSTORM\BACnetServerV2\node_modules\bacstack\lib\bacnet-client.js:343:5)
    at self.receiveData (C:\WEBSTORM\BACnetServerV2\node_modules\bacstack\lib\bacnet-client.js:354:7)
    at Socket.<anonymous> (C:\WEBSTORM\BACnetServerV2\node_modules\bacstack\lib\bacnet-transport.js:13:25)
    at Socket.emit (events.js:182:13)
    at UDP.onMessage [as onmessage] (dgram.js:670:8)
    ```
Any suggestions?
Where I can see what it means ' Class:1 - Code:31' ?

Thank you in advance!

PS. I have no problem with Binary Value type to read & write. AI/AO/BI/AV also OK.

**Comment by fh1ch** [comment]
Hi @Panibrat 

The error you describe is on application level and means: `OBJECT`- `UNKNOWN_OBJECT`.

Here is an (*unfinished*) FAQ entry I'm currently working on:

```md
## I receive the error `BacnetError - Class: X - Code: Y`. What does this mean?

The two error types `BacnetError` and `BacnetAbort` are application level errors
and are returned by a BACnet remote device in case of a failure. Both error
types also contain the reason for the failure, which can be interpreted like:

```txt
Error: BacnetError - Class: [X] - Code: [Y]
[X] => In `lib/enum.js` see `ErrorClass`.
[Y] => In `lib/enum.js` see `ErrorCode`.

Error: BacnetAbort - Reason: [Z]
[Z] => In `lib/enum.js` see `RejectReason`.
```

We therefore can encode the example `Error: BacnetError - Class: 2 - Code: 32`
to `Error: BacnetError - Class: PROPERTY - Code: UNKNOWN_PROPERTY`,  meaning the
property we tried to read or modify doesn't exist.
```

Cheers

**Comment by Panibrat** [comment]
Hello Fabio.

What wrong from my side?

Response from reading:
```
  objectId: { type: 4, instance: 3000412 },
  property: { propertyIdentifier: 85, propertyArrayIndex: 4294967295 },
  valueList: [ { len: 2, type: 9, value: 1 } ] }
```
Why UNKNOWN_PROPERTY when writing?

Binary Value works nice.

Thank you for your help!
