### ISSUE TITLE
Using with

### ISSUE THREAD

**Issue by dushyantbangal** [fh1ch/node-bacstack#140]
Node Version: `8`

Node BACstack Version: `"0.0.1-beta.13"`

- [ ] Bug Report
- [x] Feature Request
- [x] Question

**Note:** Make sure you have read the [FAQs](https://github.com/fh1ch/node-bacstack/blob/master/FAQ.md)
before logging this issue.

### Feature Request / Question

-
I have a bacnet router that is connecting MSTP to IP.
Is it possible to read the data from the devices under it? I am able to read the properties of the router, but not the devices under it.

I am able to read the data from YABE

![image](https://user-images.githubusercontent.com/13764676/62820881-9918da80-bb88-11e9-8192-ad410816e246.png)

-

**Comment by NateZimmer** [comment]
See #48 , I have a fork that does this but its not well tested nor fully complete. Needs proper tests & vetting of all the services before its up to spec with the rest of this repo for a PR.

**Comment by dushyantbangal** [comment]
@NateZimmer I had a look at your fork, even tried using it. But I think I was doing something wrong with the `net` and `adr`. I didnt fully understand it, as I'm new to bacnet. I post a detailed issue over there as well.

**Comment by dushyantbangal** [comment]
@NateZimmer this is my bacnet router's configuration:
![image](https://user-images.githubusercontent.com/13764676/62850715-5af2f680-bd01-11e9-8011-5813b27b64b8.png)

What should be my settings? I see the devices do have unique instance ids across the network, but the properties inside the devices have unique instance ids only under that device, and not across the whole network.

So far I have been able to read only the properties on the router device.

**Comment by NateZimmer** [comment]
Hey @dushyantbangal, first you should use that fork and perform a who-is on the same subnet as that router. 

If you have MSTP devices on that router & the router is functioning properly, you should get a response back from the router with those devices. 

```js
 client.whoIs({'address':{'net':0xFFFF,'ip':'xxx.xxx.xxx.255'}});
```
Device iAM responses from the router should have a `net` and `adr`. 

You can then read objects from those devices like so:

```js
client.readProperty( {'ip':'192.168.1.166','net':2000,'adr':[9]} , {type: 8, instance: 532663}, 85, (err, value) => {
  console.log('value: ', value);
});
```

**Comment by dushyantbangal** [comment]
> Device iAM responses from the router should have a net and adr.
Great!

But for some weird reason, on Ubuntu Virtual Box inside Windows, I was not getting any response on who-is. I was getting response to readProperty, on the router properties and other direct BACnet IP devices.

While on Windows, I was just getting responses for who-is and nothing on readProperty.

I'll have to try it again once I get access to the network.

**Comment by RBrothersBSI** [comment]
In this a little late. I am able to get the read request working through the router, but am unable to get the write properties to work. I am defining it exactly as in the read requests, but no luck. I can write to the values in the router just fine, just not the controller on the other side. Any ideas?

**Comment by NateZimmer** [comment]
@RBrothersBSI use wireshark to capture the packet your who-is responses from the router as well as the write property request being sent to the router. Wireshark can help verify if the packet is being formatted correctly as well as a clue as to what might be going wrong.

**Comment by RBrothersBSI** [comment]
Bingo. Using wireshark I was able to see what the issue was. 
![priorityZero](https://user-images.githubusercontent.com/52111228/74610673-e9826f00-50ba-11ea-830d-23cd56328ef1.PNG)
By default it was attempting to write at priority zero and I wasn't providing it any options. In the write property method in client.js I added || 16 to settings.priority to give it a fallback if not provided. Thank you, sir!

**Comment by Apollon77** [comment]
These changes should also be incorporated int https://github.com/BiancoRoyal/node-bacstack, please try this package and open issues at https://github.com/BiancoRoyal/node-bacstack/issues if it does not work as expected

**Comment by mwitt1337** [comment]
client.whoIs({'address':{'net':0xFFFF,'ip':'xxx.xxx.xxx.255'}});

Nate I tried this with your fork and it throws a RTE

dgram.js:396
    throw new ERR_INVALID_ARG_TYPE('address', ['string', 'falsy'], address);
    ^

TypeError [ERR_INVALID_ARG_TYPE]: The "address" argument must be one of type string or falsy. Received type object
    at Socket.send (dgram.js:396:11)
    at module.exports.self.send (C:\zimmer-bacstack\node-bacstack\node_modules\bacstack\lib\transport.js:38:12)
    at EventEmitter.self.whoIs (C:\zimmer-bacstack\node-bacstack\node_modules\bacstack\lib\client.js:403:15)
    at Object.<anonymous> (C:\zimmer-bacstack\node-bacstack\index.js:38:8)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:742:12)

I am trying to read the properties of an MS/TP device and so far I've had no luck with multiple forks.

YABE gives me an error when trying to read the child objects.
![image](https://user-images.githubusercontent.com/26658718/87955514-dd407a80-ca7b-11ea-9e72-54bf80f39369.png)

**Comment by Apollon77** [comment]
@mwitt1337 Can you please try the fork https://github.com/BiancoRoyal/node-bacstack !?

**Comment by mwitt1337** [comment]
I tried the fork https://github.com/BiancoRoyal/node-bacstack
I modified the \examples\read-device.js file line 471 to this:
bacnetClient.whoIs({'address':{'net':0xFFFF,'ip':'xxx.xxx.xxx.255'}});

And I get this error:

PS C:\BiancoRoyal\node-bacstack-master\examples> node read-device.ks
internal/modules/cjs/loader.js:583
    throw err;
    ^

Error: Cannot find module 'C:\BiancoRoyal\node-bacstack-master\examples\read-device.ks'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
    at Function.Module._load (internal/modules/cjs/loader.js:507:25)
    at Function.Module.runMain (internal/modules/cjs/loader.js:742:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:743:3)
PS C:\BiancoRoyal\node-bacstack-master\examples> node read-device.js
sent whoIs 1595351868157
C:\BiancoRoyal\node-bacstack-master\lib\transport.js:67
    const [address, port] = receiver.split(':');
                                     ^

TypeError: receiver.split is not a function or its return value is not iterable
    at Transport.send (C:\BiancoRoyal\node-bacstack-master\lib\transport.js:67:38)
    at Client.sendBvlc (C:\BiancoRoyal\node-bacstack-master\lib\client.js:1618:21)
    at Client.whoIs (C:\BiancoRoyal\node-bacstack-master\lib\client.js:601:10)
    at Client.bacnetClient.on (C:\BiancoRoyal\node-bacstack-master\examples\read-device.js:471:16)
    at Client.emit (events.js:182:13)
    at Transport.Client._transport.on (C:\BiancoRoyal\node-bacstack-master\lib\client.js:118:48)
    at Transport.emit (events.js:182:13)
    at Socket.Transport._server.on (C:\BiancoRoyal\node-bacstack-master\lib\transport.js:32:12)
    at Socket.emit (events.js:187:15)
    at startListening (dgram.js:128:10)

**Comment by mwitt1337** [comment]
I did get the WHOIS to work.

![image](https://user-images.githubusercontent.com/26658718/88088232-13ebc300-cb58-11ea-9bb4-c63a48655a18.png)

Device 156 is the MS/TP to IP router I am trying to get through. I'm not seeing the "NET" and "ADR". The readproperties of 156 did work but there isn't much there. Here is the JSON visualized

![image](https://user-images.githubusercontent.com/26658718/88088473-7644c380-cb58-11ea-89f6-8e5bb21b75ed.png)

I'm just stuck at how do I get the NET and ADR info so that I can access the devices beyond the MS/TP router? Is there something I'm not seeing in this information?

**Comment by Apollon77** [comment]
Can you please show your code? (And when you use a fork then maybe better continuing in an issue there)

**Comment by mwitt1337** [comment]
I will open an issues under the fork https://github.com/BiancoRoyal/node-bacstack
